### ISSUE TITLE
[ST2] random crashes on keystroke

### ISSUE THREAD

**Issue by crucialfelix** [srusskih/SublimeJEDI#131]
I worked for the whole day with SublimeJEDI disabled without any problem. Just enabled it again and after 10 minutes of working the random crash returns.  I've never had this crash before with ST and it was happening constantly the other day too when I first installed SublimeJEDI.

It happens on a keystroke.  Possibly when a shift modifier is down. Hard to say because its very sudden and startling.  Happens every few minutes while typing.

"settings": {
    "python_interpreter_path": "/Users/crucial/Sites/nsbuildout/bin/python"
}

auto complete is false (I thought that might be the cause)

Nothing relevant in any log.  Anything else I can look at ?

thanks !  Great plugin

**Comment by Pazitos10** [comment]
Hello, same here ST2 crashes every time I type: foo=dict(key1..<here crashes> ... This repeats any time I try to do the same.
But, when I try to write that dictionary with curly braces, I have no problems. i.e: foo = {'key1':value}
So, I think like @tonnydourado that the problem happens when we try to autocomplete inside parentheses.

Sublime version: 2.0.2 Build: 2221
SublimeJedi: 0.7.0 (I had to downgrade because 0.8.0 didn't work for me).
