### ISSUE TITLE
Function arguments - one per line

### ISSUE THREAD

**Issue by Rastko-V-P** [srusskih/SublimeJEDI#264]
Wonderful plugin, I enjoy it a lot.
Could you introduce an option to autocomplete function arguments one per line?
Example:
 ```
turn this -> enumerate(iterable, start=0)
into      -> enumerate(iterable,
                        start=0)
```
This would be particularly useful for functions with a long signature such as pd.read_csv() in combination with "auto_complete_function_params": "all".

**Comment by srusskih** [comment]
@Rastko-V-P sounds interesting! Thanks for feedback!

**Comment by edelvalle** [comment]
I personally don't like that style of indentation for parameters because is fragile to break during refactoring.
if you have

```
variable = a_function(bla1,
                      bla2)
```

and you have to rename `variable` or `a_function` you have to fix the indentation of the parameters one by one, and there could be a few of them.

Uncle Bob (Rob Martin) advises to use this way instead:

```
variable = a_function(
    bla1,
    bla2,
)
```

Adding trailing commas also, so in case you have to remove or add a parameter only one line is modified.

**Comment by Rastko-V-P** [comment]
@edalvalle Yes, that's a popular alternative, both formatting styles could be offered as an option. I still prefer the first style because it improves readability and saves 2 lines. Indentation of all parameters can be done in a single go in Sublime.

**Comment by Rastko-V-P** [comment]
Good point, solved it with [PyYapf](https://github.com/jason-kane/PyYapf), thanks for the tip.

**Comment by srusskih** [comment]
always welcome!
